branches:
  only:
  - "/^v0.*$/"
  - master
language: python
python:
- '3.5'
cache: pip
install:
- pip install --upgrade pip
- pip install --upgrade -r requirements.txt
- npm install -g jshint
sudo: required
dist: trusty
group: deprecated-2017Q4
addons:
  postgresql: '9.4'
before_script:
- mv configs/local_settings.py.travis lots/local_settings.py
- psql -U postgres -c "CREATE DATABASE largelots"
- python manage.py migrate
script:
- pytest
- jshint --extract=always templates/*
- jshint lots/static/js/largelots_emailcheck.js
notifications:
  webhooks:
    - https://semabot.datamade.us/travis/

deploy:
  - provider: codedeploy
    access_key_id: AKIAJNYGDLOJKHOUWCAA
    secret_access_key:
      secure: a9lv+69yYibCSr3vqNwg5FK3v8KVPj08BhWyeDVi4Fnd/sxKZ/kKjFABy+ALJXJyXQyFSup13eLaggyIrHGG+LP3YfND9WKxhFb+8hCEu+YiRmXIEaJJcr2hmHPRPEVzeJmfpOWhIG/DrEYGcQVr+KpSIcINRiXsVTMRjij8UkA=
    application: large-lots
    deployment_group: staging
    on:
      branch: master

  - provider: codedeploy
    access_key_id: AKIAJNYGDLOJKHOUWCAA
    secret_access_key:
      secure: a9lv+69yYibCSr3vqNwg5FK3v8KVPj08BhWyeDVi4Fnd/sxKZ/kKjFABy+ALJXJyXQyFSup13eLaggyIrHGG+LP3YfND9WKxhFb+8hCEu+YiRmXIEaJJcr2hmHPRPEVzeJmfpOWhIG/DrEYGcQVr+KpSIcINRiXsVTMRjij8UkA=
    application: large-lots
    deployment_group: production
    on:
      tags: true
