# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lots_admin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('street_number', models.CharField(max_length=10, null=True)),
                ('street_dir', models.CharField(max_length=2, null=True)),
                ('street_name', models.CharField(max_length=50, null=True)),
                ('street_type', models.CharField(max_length=10, null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('city', models.CharField(default='Chicago', max_length=20)),
                ('state', models.CharField(default='IL', max_length=20)),
                ('zip_code', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('organization', models.CharField(max_length=255, null=True)),
                ('owned_pin', models.CharField(max_length=14)),
                ('deed_image', models.FileField(upload_to=lots_admin.models.upload_name)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255, null=True)),
                ('how_heard', models.CharField(max_length=255, null=True)),
                ('tracking_id', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=50, null=True)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('pilot', models.CharField(max_length=50, null=True)),
                ('contact_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_address', to='lots_admin.Address')),
                ('owned_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_address', to='lots_admin.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('pin', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('planned_use', models.CharField(default=None, max_length=20, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots_admin.Address')),
                ('application', models.ManyToManyField(to='lots_admin.Application')),
            ],
        ),
    ]
