# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lots_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('public_status', models.CharField(max_length=255)),
                ('email_sent', models.BooleanField()),
                ('denied', models.BooleanField(default=False)),
                ('step', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DenialReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('step', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='denial_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots_admin.DenialReason'),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
