# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0002_auto_20160912_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='denial_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lots_admin.DenialReason'),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
