# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0006_auto_20160912_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reviewstatus',
            name='application_status',
        ),
        migrations.AddField(
            model_name='application',
            name='app_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lots_admin.ApplicationStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='review_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lots_admin.ReviewStatus'),
        ),
    ]
