
# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0007_auto_20160913_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='app_status',
            new_name='status',
        ),
    ]
