# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 21:20
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0009_auto_20160913_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
    ]
