# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0010_reviewstatus_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewstatus',
            name='created_at',
        ),
    ]
