# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 14:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0011_remove_reviewstatus_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 16, 14, 0, 24, 280006, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
