# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0012_reviewstatus_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='review_status',
        ),
        migrations.AddField(
            model_name='reviewstatus',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lots_admin.Application'),
        ),
    ]
