# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0013_auto_20160916_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denialreason',
            name='step',
        ),
        migrations.AddField(
            model_name='reviewstatus',
            name='step',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
