# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0014_auto_20160916_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewstatus',
            old_name='step',
            new_name='step_completed',
        ),
    ]
