# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0016_auto_20160916_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('public_status', models.CharField(max_length=255)),
                ('step', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ReviewStatus',
            new_name='ApplicationReview',
        ),
        migrations.RemoveField(
            model_name='application',
            name='denied',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.RemoveField(
            model_name='applicationstatus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='applicationstatus',
            name='public_status',
        ),
        migrations.RemoveField(
            model_name='applicationstatus',
            name='step',
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lots_admin.Application'),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lots_admin.Lot'),
        ),
        migrations.AlterField(
            model_name='applicationreview',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lots_admin.ApplicationStatus'),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='application_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lots_admin.ApplicationStep'),
        ),
    ]
