# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0017_auto_20160920_1412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationReview',
            new_name='Review',
        ),
        migrations.RenameField(
            model_name='applicationstatus',
            old_name='application_step',
            new_name='current_step',
        ),
    ]
