# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0018_auto_20160920_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.CharField(default='reginafcompton@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
