# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0019_auto_20160926_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='ward',
            field=models.CharField(default=28, max_length=255),
            preserve_default=False,
        ),
    ]
