# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0021_auto_20160927_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ward',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
