# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0023_auto_20160927_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='step_completed',
            field=models.IntegerField(null=True),
        ),
    ]
