# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0025_auto_20161129_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_dir',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='ward',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
