# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0030_application_deed_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatus',
            name='lottery',
            field=models.BooleanField(default=False),
        ),
    ]
