# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0032_applicationstatus_eds_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstatus',
            name='eds_sent',
        ),
        migrations.AddField(
            model_name='application',
            name='eds_sent',
            field=models.BooleanField(default=False),
        ),
    ]
