# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0033_auto_20170710_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatus',
            name='lottery_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
