# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0034_applicationstatus_lottery_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='closing_invite_sent',
            field=models.BooleanField(default=False),
        ),
    ]
