# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-04 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0035_application_closing_invite_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('social_security_number', models.CharField(max_length=11)),
                ('drivers_license_number', models.CharField(max_length=20)),
                ('license_plate_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots_admin.Application')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_address', to='lots_admin.Address')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots_admin.Application')),
            ],
        ),
        migrations.AddField(
            model_name='principalprofile',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lots_admin.RelatedPerson'),
        ),
    ]
