# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-06 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0035_application_closing_invite_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('social_security_number', models.CharField(max_length=11)),
                ('drivers_license_number', models.CharField(max_length=20)),
                ('license_plate_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='lots_admin.Application')),
            ],
        ),
    ]
