# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-31 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0036_application_organization_confirmed'),
        ('lots_admin', '0036_principal_profile'),
    ]

    operations = [
    ]
