# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0036_auto_20180104_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='eds_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='ppf_received',
            field=models.BooleanField(default=False),
        ),
    ]
