# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0036_auto_20180104_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='eds_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='ppf_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='principalprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='principalprofile',
            name='drivers_license_state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='principalprofile',
            name='exported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='principalprofile',
            name='license_plate_state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='principalprofile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='principalprofile',
            name='drivers_license_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='principalprofile',
            name='license_plate_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='principalprofile',
            name='social_security_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
