# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-06 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0037_merge_20180131_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_use', models.CharField(max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots_admin.Application')),
            ],
        ),
        migrations.RemoveField(
            model_name='lot',
            name='planned_use',
        ),
        migrations.AddField(
            model_name='lotuse',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots_admin.Lot'),
        ),
    ]
