# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-19 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0038_add_lot_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='principalprofile',
            name='org_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
