# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-29 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lots_admin', '0039_ppf_org_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatedEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('owned_pin', models.CharField(max_length=14, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lots_admin.Application')),
            ],
            options={
                'verbose_name_plural': 'UpdatedEntities',
            },
        ),
    ]
