# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-19 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0039_ppf_org_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='principalprofile',
            old_name='org_address',
            new_name='organization_address',
        ),
    ]
