# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots_admin', '0040_updatedentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatus',
            name='is_resident',
            field=models.NullBooleanField(),
        ),
    ]
